# Generated by Django 4.2.10 on 2025-05-24 14:26

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        auto_now_add=True,
                        help_text="date created",
                        null=True,
                        verbose_name="date created",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Write source news",
                        max_length=255,
                        verbose_name="source",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Write title news",
                        max_length=512,
                        verbose_name="title",
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        help_text="Write abaout news", verbose_name="about"
                    ),
                ),
                (
                    "link",
                    models.TextField(
                        help_text="Write link news", verbose_name="link"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "news",
                "verbose_name_plural": "news",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Note image/profile avatar",
                        null=True,
                        upload_to=apps.core.models.BaseImageModel.upload_to_path,
                        verbose_name="image/avatar",
                    ),
                ),
                (
                    "news",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.news",
                        verbose_name="image",
                    ),
                ),
            ],
            options={
                "verbose_name": "image news",
                "verbose_name_plural": "images news",
            },
        ),
    ]
